"""Add name column to users

Revision ID: 63fa2c9c0f95
Revises: add_invoice_currency
Create Date: 2025-11-14 12:44:56.167053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63fa2c9c0f95'
down_revision: Union[str, Sequence[str], None] = 'add_invoice_currency'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cc', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['cc'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'cc')
    # ### end Alembic commands ###
